version: '3.8'
services:
  db:
    image: bitnami/mysql:latest
    stop_grace_period: 60s
    volumes:
      - "../.tt/data/sql:/docker-entrypoint-initdb.d:cached"
    restart: "no"
    user: root
    ports:
      - 3306
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_ROOT_PASSWORD=root
      - VIRTUAL_HOST=db.${PROJECT_NAME}.${PROJECT_VENDOR}.docker
      - DNSDOCK_ALIAS=db.${PROJECT_NAME}.${PROJECT_VENDOR}.docker

  app:
    image: php:7.4.8-apache
    build:
      context: ../
      dockerfile: .tt/config/docker/dockerfiles/Dockerfile.app
    volumes:
      - "../:/var/www/html:cached"
      - "../.cache/composer:/var/www/.composer:cached"
    restart: "no"
    #user: "$DEV_UID:$DEV_GID"
    depends_on:
      - db
    links:
      - db:db
    ports:
      - 8080:80
    working_dir: /var/www/html
    environment:
      - OPCACHE_ENABLED=0
      - DB_SCHEMA=mysql
      - DB_HOST=db
      - DB_NAME=drupal
      - DB_USER=drupal
      - DB_PASS=drupal
      - DB_PORT=3306
      - DB_PREFIX=
      - DRUPAL_PREPROCESS_CSS=0
      - DRUPAL_PREPROCESS_JS=0
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=app.${PROJECT_NAME}.${PROJECT_VENDOR}.docker
      - DNSDOCK_ALIAS=app.${PROJECT_NAME}.${PROJECT_VENDOR}.docker
      - PHP_MEMORY_LIMIT=512M
      - PHP_MAX_EXECUTION_TIME=360
      - COMPOSER_MEMORY_LIMIT=-1

  # Database Managment
  dba:
    image: adminer:4.7.7-standalone
    depends_on:
      - db
    links:
      - db:db
    ports:
      - 8081:8080
    environment:
      - VIRTUAL_HOST=adminer.${PROJECT_NAME}.${PROJECT_VENDOR}.docker
      - DNSDOCK_ALIAS=adminer.${PROJECT_NAME}.${PROJECT_VENDOR}.docker

  # Mail Management
  mail:
    image: mailhog/mailhog:latest
    ports:
      - 8082:8025
    environment:
      - VIRTUAL_HOST=mailhog.${PROJECT_NAME}.${PROJECT_VENDOR}.docker
      - DNSDOCK_ALIAS=mailhog.${PROJECT_NAME}.${PROJECT_VENDOR}.docker
